version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/New_York  # Change this to your timezone
      - TZ=America/New_York               # Change this to your timezone
      - N8N_SECURE_COOKIE=false           # Set to true if using HTTPS
      - WEBHOOK_URL=http://localhost:5678/ # Change if using different URL
      - N8N_METRICS=true                  # Enable metrics (optional)
      # Uncomment the following lines if you want to use PostgreSQL instead of SQLite
      # - DB_TYPE=postgresdb
      # - DB_POSTGRESDB_HOST=postgres
      # - DB_POSTGRESDB_PORT=5432
      # - DB_POSTGRESDB_DATABASE=n8n
      # - DB_POSTGRESDB_USER=n8n
      # - DB_POSTGRESDB_PASSWORD=n8n
    volumes:
      - ./n8n_data:/home/node/.n8n
      # If you want to import your current workflows and data:
      # - ./database.sqlite:/home/node/.n8n/database.sqlite
      # - ./workflows:/home/node/.n8n/workflows
    # Uncomment if you want to use PostgreSQL
    # depends_on:
    #   - postgres

  # Uncomment this section if you want to use PostgreSQL instead of SQLite
  # postgres:
  #   image: postgres:15
  #   container_name: n8n-postgres
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=n8n
  #     - POSTGRES_PASSWORD=n8n
  #     - POSTGRES_DB=n8n
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: